spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://rc1d-u65z2n58k5x48jw0.mdb.yandexcloud.net:6432/chomik-gateway
    username: chomik
    password: ${DB_PASSWORD}

chomik:
  storage:
    url: http://chomik-storage-balancer:80
  order:
    url: http://chomik-order:17003
  payment:
    url: http://chomik-payment:17004
  delivery:
    url: http://chomik-delivery:17002

bank:
  user:
    id: {BANK_USER_ID}
