spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://rc1d-u65z2n58k5x48jw0.mdb.yandexcloud.net:6432/chomik-delivery
    username: chomik
    password: ${DB_PASSWORD}

delivery:
  mock:
    url: http://delivery-mock:17005
