spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://rc1b-jyoibej2wl1zryew.mdb.yandexcloud.net:6432/chomik?targetServerType=master&ssl=true&sslmode=verify-full
    username: chomik
    password: 12345678


expired:
  reservation:
    job:
      lock:
        timeout: 900
      cron: 0 0/5 * ? * * *

server:
  port: 17004