spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${ORDERS_DB_URL}
    username: ${ORDERS_DB_USERNAME}
    password: ${ORDERS_DB_PASSWORD}


expired:
  reservation:
    job:
      lock:
        timeout: 900
      cron: 0 0/5 * ? * * *
