server:
  port: 8081

spring:
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  profiles:
    active: ${ENVIRONMENT}

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never


lock:
  delta: 30
