server:
  port: 17001

spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  profiles:
    active: ${ENVIRONMENT}

datasource:
  storage:
    url:
    database:
    username:
    password:
    server:
    port:
    liquibase:
      change-log:
  sales:
    url:
    database:
    username:
    password:
    server:
    port:
    liquibase:
      change-log:
