spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://rc1d-u65z2n58k5x48jw0.mdb.yandexcloud.net:6432/chomik-payment
    username: chomik
    password: ${DB_PASSWORD}

server:
  port: 17004

payment:
  mock:
    url: http://localhost:17006

chomik:
  order:
    url: http://localhost:17003

gateway:
  host: http://localhost:17000
